# Chapter 02: Vectors, Part 1

## Concepts

In [2]:
import numpy as np

In [6]:
# Python Lists and Numpy Arrays

asList = [7, 8, 9]
asArray = np.array([7, 8, 9]) # 1D array
rowVec = np.array([ [7, 8, 9] ]) # row orientated vector
colVec = np.array([ [7], [8], [9] ]) #column orientated vector

print(f'asList: {np.shape(asList)}')
print(f'asArray: {asArray.shape}')
print(f'rowVec: {rowVec.shape}')
print(f'colVec: {colVec.shape}')

asList: (3,)
asArray: (3,)
rowVec: (1, 3)
colVec: (3, 1)


In [17]:
# Vector Addition
vector_a = np.array([1, 2, 3])
vector_b = np.array([15, 25 , 35])

vector_addition_result = vector_a + vector_b

vector_addition_result

array([16, 27, 38])

In [16]:
# Vector Scalar Multiplication

scalar = 3
array = np.array([4, 5, 6])

scalar_mult_result = scalar * array

scalar_mult_result

array([12, 15, 18])

In [15]:
# Scalar Vector Addition

scalar = 3
array = np.array([4, 5, 6])

scalar_add_result = scalar + array

scalar_add_result

array([7, 8, 9])

In [14]:
# Vector Broadcasting

col_vector = np.array([ [5, 10, 15] ]).T
row_vector = np.array([ [1, 2] ])

vector_broadcasting_result = col_vector + row_vector

vector_broadcasting_result

array([[ 6,  7],
       [11, 12],
       [16, 17]])

In [18]:
# Vector Dimensions and Magnitude

vector = np.array([3,4,5,6,7])
vector_dimensions = len(vector)
vector_magnitude = np.linalg.norm(vector)

print(vector_dimensions)
print(vector_magnitude)

5
11.61895003862225


In [19]:
# Vector Dot Product
vector_a = np.array([1, 2, 3])
vector_b = np.array([15, 25 , 35])

vector_dot_product = np.dot(vector_a, vector_b)

vector_dot_product

170

In [20]:
# Distributive Property Intuition
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
vector_c = np.array([10, 20 ,30])

res1 = np.dot(vector_a, vector_b + vector_c)
res2 = np.dot(vector_a, vector_b) + np.dot(vector_a, vector_c)

print(res1 == res2)

True


In [21]:
# Hadamard Multiplication (Element-wise)

vector_a = np.array([1, 2, 3])
vector_b = np.array([15, 25 , 35])

vector_dot_product = vector_a * vector_b

vector_dot_product

array([ 15,  50, 105])

In [22]:
# Vector Outer Product

vector_a = np.array([1, 2, 3])
vector_b = np.array([15, 25 , 35])

vector_dot_product = np.outer(vector_a, vector_b)

vector_dot_product

array([[ 15,  25,  35],
       [ 30,  50,  70],
       [ 45,  75, 105]])

## Code Exercises