# Chapter 10: Row Reduction & LU Decomposition

## Concepts

In [21]:
import numpy as np
import sympy as sym
import scipy.linalg

In [13]:
# Solving Matrix Equations (Ax=B)

matrix_a = np.random.randn(4, 4)
matrix_b = np.random.randn(4, 4)

# Correct answer (pre-multiply)
matrix_x1 = np.linalg.inv(matrix_a) @ matrix_b

# Incorrect answer (post-multiply)
matrix_x2 = matrix_b @ np.linalg.inv(matrix_a)

# Calculate residuals
residual_1 = (matrix_a @ matrix_x1) - matrix_b
residual_2 = matrix_a @ matrix_x2 - matrix_b

print("Residual from Method 1 is close to zeros matrix:", np.allclose(np.zeros((4,4)), residual_1))
print("Residual from Method 2 is close to zeros matrix:",np.allclose(np.zeros((4,4)), residual_2))

Residual from Method 1 is close to zeros matrix: True
Residual from Method 2 is close to zeros matrix: False


In [19]:
# RREF (Row-Reduced Echelon Form) via Gauss-Jordan Elimination

# Create matrix equation matrix in sympy
matrix_a = np.array([
    [1, 1 ,4],
    [-1/2, 1, 2]
])
symMat = sym.Matrix(matrix_a)

# RREF via Gauss-Jordan Elimination
symMat.rref()[0]

Matrix([
[1, 0, 1.33333333333333],
[0, 1, 2.66666666666667]])

In [25]:
# LU Decomposition

# Perform LU Decomposition
matrix_a = np.array([
    [2, 2, 4],
    [1, 0, 3],
    [2, 1, 2]
])

_, L, U = scipy.linalg.lu(matrix_a)

print("Lower Triangular Matrix: ", "\n", L, "\n" )
print("Upper Triangular Matrix: ", "\n", U)

Lower Triangular Matrix:  
 [[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]] 

Upper Triangular Matrix:  
 [[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]


## Code Exercises

In [ ]:
# Exercise 10-1 (TimingLU decompositions on 1K 100x100 matrices)

In [ ]:
# Exercise 10-2 (Matrix Ranks, Original and LU decomposed)

In [ ]:
# Exercise 10-3 (Calculating Matrix Determinant via outputs of LU Decomposition)

In [ ]:
# Exercise 10-4 (Calculating Matrix Inverse via outputs of LU Decomposition)

In [ ]:
# Exercise 10-5 (Matrix Equivalence: Comparing A^T @ A Computed Directly and via LU Decomposition)