# Chapter 13: Eigendecomposition

# Concepts

In [1]:
import numpy as np
import scipy
import matplotlib.pyplot as plt

In [2]:
# Finding eigenvalues

matrix_a = np.array([
    [1, 2],
    [3, 4]
])

evals = np.linalg.eigh(matrix_a)[0]
print(evals)

[-0.85410197  5.85410197]


In [4]:
# Finding eigenvectors

evecs = np.linalg.eigh(matrix_a)[1]
print(evecs)

[[-0.85065081  0.52573111]
 [ 0.52573111  0.85065081]]


In [5]:
# Diagonalizing a matrix

diag_matrix_a = np.diag(evals)
print(diag_matrix_a)

[[-0.85410197  0.        ]
 [ 0.          5.85410197]]


In [11]:
# Orthogonal Eigenvectors

# Create a symmetrical matrix
random_matrix_a = np.random.randint(-3, 4, (3, 3))
symmetrical_matrix_a = random_matrix_a.T @ random_matrix_a

# perform eigendecomposition
evals, evecs = np.linalg.eigh(symmetrical_matrix_a)

# compute all pair-wise dot products of eigenvectors matrix
dot_product_1 = np.dot(evecs[:,0], evecs[:,1])
dot_product_2 = np.dot(evecs[:,0], evecs[:,2])
dot_product_3 = np.dot(evecs[:,1], evecs[:,2])
check = np.isclose(dot_product_1, 0) and np.isclose(dot_product_2, 0) and np.isclose(dot_product_3, 0)

print("All pair-wise dot products of the eigenvectors for a symmetrical matrix are equal to zero:", check)

All pair-wise dot products of the eigenvectors for a symmetrical matrix are equal to zero: True


In [13]:
# Real-valued eigenvalues (symmetrical matrix)

matrix_a = np.array([
    [-3, -3, 0],
    [-3, -2, 1],
    [0, 1, 2]
])

evals, evecs = np.linalg.eig(matrix_a)

print(evals.reshape(-1, 1))

[[-5.59707146]
 [ 0.22606174]
 [ 2.37100972]]


In [17]:
# Eigendecomposition of singular matrices

singular_matrix_a = np.array([
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9]
])

evals, evecs = np.linalg.eig(singular_matrix_a)

print(f"Rank = {np.linalg.matrix_rank(singular_matrix_a)} \n")
print(f"Eigenvalues: {np.round(evals, 2)} \n")
print(f"Eigenvectors: {np.round(evecs, 2)} \n")

Rank = 2 

Eigenvalues: [16.12 -1.12 -0.  ] 

Eigenvectors: [[-0.46 -0.88  0.41]
 [-0.57 -0.24 -0.82]
 [-0.68  0.4   0.41]] 



In [18]:
# Generalized eigendecomposition

# create correlated matrices
random_matrix_a = np.random.randn(4, 4)
matrix_a = random_matrix_a.T @ random_matrix_a
random_matrix_b = np.random.randn(4, 4)
matrix_b = random_matrix_b.T @ random_matrix_b + matrix_a / 10

evals, evecs = scipy.linalg.eigh(matrix_a, matrix_b)
print(f"Eigenvalues: {np.round(evals, 2)} \n")
print(f"Eigenvectors: {np.round(evecs, 2)} \n")

Eigenvalues: [0.02 0.07 1.32 2.97] 

Eigenvectors: [[ 0.31  0.34 -0.08 -0.25]
 [-0.07  0.06 -0.34 -0.44]
 [ 0.08  0.37 -0.23  0.31]
 [-0.24  0.27  0.54 -0.01]] 



# Code Exercises

In [ ]:
# Exercise 13-1 ()

In [ ]:
# Exercise 13-2 ()

In [ ]:
# Exercise 13-3 ()

In [ ]:
# Exercise 13-4 ()

In [ ]:
# Exercise 13-5 ()

In [ ]:
# Exercise 13-6 ()

In [ ]:
# Exercise 13-7 ()

In [ ]:
# Exercise 13-8 ()

In [ ]:
# Exercise 13-9 ()

In [ ]:
# Exercise 13-10 ()

In [ ]:
# Exercise 13-11 ()